import next_text from "@/utils/font";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "FQ Landing ",
  description: "Generated by tarifalhasan999@gmail.com",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/next.svg"
          type="/next.svg"
          sizes="<generated>"
        />
      </head>
      <body className={next_text.className}>{children}</body>
    </html>
  );
}
